### ISSUE TITLE
linux64 (probably also 32) not working on windows

### ISSUE THREAD

**Issue by ocean1** [phretor/memory-errors-lab#7] opened 2015-12-15 18:04 UTC
it crashes with rsync under cygwing

probably: https://github.com/mitchellh/vagrant/issues/4073
is there any way we can setup a workaround?

**Comment by phretor** [comment] 2015-12-15 18:30
Is it really Windows 7? Can we reproduce this?

**Comment by ocean1** [comment] 2015-12-15 21:10
The students were using windows 10, yes, with a windows machine at three
students experienced the same issue.

D.

On 15 December 2015 at 19:34, Federico Maggi notifications@github.com
wrote:

> Is it really Windows 7? Can we reproduce this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phretor/memory-errors-lab/issues/7#issuecomment-164849404
> .

## 

会うは別れの始め

**Comment by phretor** [comment] 2015-12-15 21:17
Great. Let's have a debug trace or something :)

**Comment by andres-fps** [comment] 2015-12-16 14:18
Hi

After: vagrant up, I got this error:

(I'm working on a Windows 8.1 pro machine, 64 bits)

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian/jessie64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'debian/jessie64' is up to date...
==> default: Setting the name of the VM: linux64_default_1450275279968_63121
"rsync" could not be found on your PATH. Make sure that rsync
is properly installed on your system and available on the PATH.
```

**Comment by ocean1** [comment] 2015-12-16 15:08
are you using a windows machine? if so you should install cygwin/rsync or
mingw/rsync but it will crash then, not allowing the correct bootstrap of
the machine right now, it's probably a cygwin/vagrant bug that should be
investigated further for a workaround.

D.

On 16 December 2015 at 15:18, felipe07 notifications@github.com wrote:

> Hi
> 
> After: vagrant up, I got this error:
> 
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Importing base box 'debian/jessie64'...
> ==> default: Matching MAC address for NAT networking...
> ==> default: Checking if box 'debian/jessie64' is up to date...
> ==> default: Setting the name of the VM: linux64_default_1450275279968_63121
> "rsync" could not be found on your PATH. Make sure that rsync
> is properly installed on your system and available on the PATH.
> 
> Can you help me?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/phretor/memory-errors-lab/issues/7#issuecomment-165122564
> .

## 

会うは別れの始め

**Comment by phretor** [comment] 2015-12-16 17:09
Please install rsync and give us the error traceback, if any, when you
retry the installation.

Thanks!

**Comment by andres-fps** [comment] 2015-12-16 18:34
I reinstalled rsync but the problem persisted, however after I added to the path (environment variable) of windows the route to rsync (C:\cygwin64\bin) the problem was solved.

Thanks.

**Comment by phretor** [comment] 2015-12-16 22:20
Cool, then we can close this.

**Closed as completed by phretor** 2015-12-16 22:20 UTC
